name: calculator
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  localization: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations: # add this line
    sdk: flutter        # add this line
  intl: ^0.17.0
  math_expressions:
    git:
      url: https://github.com/danger-ahead/math-expressions.git
      ref: add-degree-hack
  flutter_riverpod: ^1.0.3
  shared_preferences: ^2.0.11
  flutter_vibrate: ^1.3.0
  url_launcher: ^6.0.17
  flutter_neumorphic: ^3.2.0
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  path: ^1.8.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

assets:
  - assets/
